#!/bin/sh

set -eux

# Generate SSL if the folder is not found.
if [ ! -d '/etc/nginx/ssl' ]; then
  mkdir /etc/nginx/ssl
  openssl req -new -x509 -newkey rsa:2048 -nodes -out /etc/nginx/ssl/cert.crt -keyout /etc/nginx/ssl/cert.key -subj "/C=US/ST=Kansas/L=Eudora/O=DOM/OU=DOM/CN=*"
fi
